server:
  port: ${PORT:8080}

spring:
  application:
    name: re-shopping-cart-web-app

  profiles:
    # active: prod # Production development
    active: local # Local development

  datasource:
    url: mysql://root:YcMAuiUsjQqRwfZaadyzxqZtYiuelYrI@nozomi.proxy.rlwy.net:24051/railway
    username: root
    password: YcMAuiUsjQqRwfZaadyzxqZtYiuelYrI
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  thymeleaf:
    cache: false
